pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=Lint code base
      - check-success=Assert project can build (12.x)
      - check-success=Assert project can build (13.x)
      - check-success=Assert project can build (14.x)
      - check-success=Assert project can build (15.x)
      - check-success=Dependency Security Audit (12.x)
      - check-success=Dependency Security Audit (13.x)
      - check-success=Dependency Security Audit (14.x)
      - check-success=Dependency Security Audit (15.x)
      - check-success=WIP
    actions:
      merge:
        method: merge
  - name: automatic merge for ImgBot pull requests
    conditions:
      - author=imgbot[bot]
      - check-success=Lint code base
      - check-success=Assert project can build (12.x)
      - check-success=Assert project can build (13.x)
      - check-success=Assert project can build (14.x)
      - check-success=Assert project can build (15.x)
      - check-success=Dependency Security Audit (12.x)
      - check-success=Dependency Security Audit (13.x)
      - check-success=Dependency Security Audit (14.x)
      - check-success=Dependency Security Audit (15.x)
      - check-success=WIP
    actions:
      merge:
        method: merge
  - name: Automatic merge ⬇️ on approval ✔
    conditions:
      - "#approved-reviews-by>=2"
      - check-success=Lint code base
      - check-success=Assert project can build (12.x)
      - check-success=Assert project can build (13.x)
      - check-success=Assert project can build (14.x)
      - check-success=Assert project can build (15.x)
      - check-success=Dependency Security Audit (12.x)
      - check-success=Dependency Security Audit (13.x)
      - check-success=Dependency Security Audit (14.x)
      - check-success=Dependency Security Audit (15.x)
      - check-success=WIP
    actions:
      merge:
        method: merge
